//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowTyper.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FollowTyper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 儿童是祖国的未来，民族的希望。亿万儿童能否健康成长，关系到国家的前途命运，关系到党的事业的兴衰成败。做好儿童工作，发展儿童事业，培养造就一代新人，是提高民族素质的一项基础工程，是实现我们宏伟目标的重要保证，是社会主义现代化建设事业兴旺发达的必然要求。我们党和政府历来关心和重视儿童的成长，关心和重视儿童工作和儿童事业。建国以来特别是改革开放以来，我国的儿童工作取得了很大成绩，儿童事业有了长足的发展。为了适应新形势的需要，进一步发展儿童事业，国务院制定了《九十年代中国儿童发展规划纲要》。这是我国儿童工作的一件大事，是我国政府促进儿童事业发展的重大步骤。改革开放和现代化建设事业的发展，为儿童工作创造了有利的环境和条件，注入了生机和活力，同时也向儿童工作提出了更高的要求。希望各级党委和政府要从战略的高度充分认识儿童工作的重要性，以强烈的使命感、责任感和紧迫感，把儿童工作提到议事日程，切实加强对儿童工作的领导。各地各部门要结合自己的实际，积极创造条件，采取有效措施，把规划纲要贯彻好、落实好。关心和促进儿童的健康成长，也是每个公民应尽的义务和神圣职责，“爱护儿童，教育儿童，为儿童做表率，为儿童办实事”，应当成为每个公民的 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 儿童是祖国的未来 {
            get {
                return ResourceManager.GetString("儿童是祖国的未来", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采项装入同小林几主文做看重很知南办江计许最统记提向为走积题长张及道拉港动众该神关加此具反定将合次价传气引年他部营民理观议机并每后场书各识量么查思高投表地女优家打点件际手风信期心院它省委易举下先社样转性深工志受究设又特司果农而职华革争持效厂参报比仅保内准常产北也于推研去出可济们资京结首五如处里着界供必国护包近台四不美好话谈天日副现应协权贸中得交质军织事收山从马等月育只变战是斯少论相东那严当科西管见使放在股到区把则共面和解还第消广服被强带就造环府外极会的务上术至用三制品者海车学费平步分无本取安规力划说过来但这要对回确整问局境政款告然通料路级支身因市电时快度教两头种些形策销今单业德行实所位组益求正我多己口新商展水劳难大世想村需集发代格青标由户才城条情方作税选意体构运亚干真老联或间之乡总利直了李技县创任源名势都已门原子责企立率王金式其视改自况节万批精一完备给型起兴生值指证活明州公开队义物进法认程全光领元个员案亿团有专决与成目没施流党列系增据数较百调化治别镇经能人更前接以基达建十色二导
        /// 的本地化字符串。
        /// </summary>
        public static string 凌辱444 {
            get {
                return ResourceManager.GetString("凌辱444", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///胡锦涛在党的十七大上的报告
        ///人民网北京10月15日电中国共产党第十七次全国代表大会于15日上午9时在北京人民大会堂开幕。
        ///
        ///同志们，现在，我代表第十六届中央委员会向大会作报告。中国共产党第十七次全国代表大会，是在我国改革发展关键阶段召开的一次十分重要的大会。大会的主题是：高举中国特色社会主义伟大旗帜，以邓小平理论和“三个代表”重要思想为指导，深入贯彻落实科学发展观，继续解放思想，坚持改革开放，推动科学发展，促进社会和谐，为夺取全面建设小康社会新胜利而奋斗。
        ///
        ///中国特色社会主义伟大旗帜，是当代中国发展进步的旗帜，是全党全国各族人民团结奋斗的旗帜。解放思想是发展中国特色社会主义的一大法宝，改革开放是发展中国特色社会主义的强大动力，科学发展、社会和谐是发展中国特色社会主义的基本要求，全面建设小康社会是党和国家到二零二零年的奋斗目标，是全国各族人民的根本利益所在。
        ///
        ///当今世界正在发生广泛而深刻的变化，当代中国正在发生广泛而深刻的变革。机遇前所未有，挑战也前所未有，机遇大于挑战。全党必须坚定不移地高举中国特色社会主义伟大旗帜，带领人民从新的历史起点出发，抓住和用好重要战略机遇期，求真务实，锐意进取，继 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 十七大报告 {
            get {
                return ResourceManager.GetString("十七大报告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全面建设小康社会，开创中国特色社会主义事业新局面
        ///——在中国共产党第十六次全国代表大会上的报告
        ///（2002年11月8日）
        ///江泽民
        ///
        ///同志们：
        ///现在，我代表第十五届中央委员会向大会作报告。
        ///中国共产党第十六次全国代表大会，是我们党在新世纪召开的第一次代表大会，也是我们党在开始实施社会主义现代化建设第三步战略部署的新形势下召开的一次十分重要的代表大会。
        ///
        ///大会的主题是：高举邓小平理论伟大旗帜，全面贯彻“三个代表”重要思想，继往开来，与时俱进，全面建设小康社会，加快推进社会主义现代化，为开创中国特色社会主义事业新局面而奋斗。
        ///
        ///当人类社会跨入二十一世纪的时候，我国进入全面建设小康社会、加快推进社会主义现代化的新的发展阶段。国际局势正在发生深刻变化。世界多极化和经济全球化的趋势在曲折中发展，科技进步日新月异，综合国力竞争日趋激烈。形势逼人，不进则退。我们党必须坚定地站在时代潮流的前头，团结和带领全国各族人民，实现推进现代化建设、完成祖国统一、维护世界和平与促进共同发展这三大历史任务，在中国特色社会主义道路上实现中华民族的伟大复兴。这是历史和时代赋予我们党的庄严使命。
        ///
        ///一、过去五年的工作和十 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 十六大报告 {
            get {
                return ResourceManager.GetString("十六大报告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 才必北公之命干空东自收次小气想受到于使说远情她都知未头己指如理南服取和交第位放手前管分西二等让由做两可因长言名一又出记更里还接年那色深性直条其国无实口而应计地思息此义信转便他最任点却高学王像电人有件反元提要与快认太来老体去么但期正所事个住几风果道数同每并办民进望见得心什大处机文合结没场流立开先度告感活打向间样军日这加明书及给回天在能它相多则本夫士下了万平目美今光眼边张已路总马从华师会字十家重特通象后题近只也连识语将法报金走中百论海三定不方话传作好水且问步力再清世即常带种看月新五当被时把子少保求林以是教算就为全儿声何系安过经花起车四生行外变用我听完至许制门主些量解们白入各或神你成女物然觉动难现意面内业真上化强形请半满的利别决工发代表比原对身部该关者很山非往着容
        /// 的本地化字符串。
        /// </summary>
        public static string 强暴333 {
            get {
                return ResourceManager.GetString("强暴333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识组标委次长过史少河得路两变银小之看效数表他张抓于开推售责亿制量清仅集原每配增当依斯西使把行育质油息者争后分界和保持相领目理游以连正局程山财日你车艺速央主么统面势天件作客书家军而江院特足支一被道需青区率解也获各术儿前为我源子接按从严技基万额三港具续政新型高采德建平务批世同反群究族八奖优收参几产品专查队办举拉的点达联会关李引投度准须运贸说未共回府业户格女内股命备受十了至所望间决规供还团重切战因快活转已事元根任节期做周头乡完千生都国那米城再强题给现里它然类多闻结着进士知打最第经在历协流无整管访本报近由县式职大案复较研影议花是司化单能这动门美告月成益带四视求志来心论热性市些难神义席款验记即干年身往用该何兴直始九学很并方段东样提评坚列今文力果走划展济利步照思人布份位工要许范装际环指处情价口防村色放等加农及创约选感立机众础权想电易信律食台讯级就税合气资黄真但全限公营上对没商种更观先校模体深革如自均亚谈石负项织尔护王物发则意她首不英与部调货代传富水便安线土通向下功设时精克示实认老海养员百中极场费低民检造断改们出存医副马构越省包条师华入科五料此据个话象系注或必策让层厂导手交教非治北比可空消房社党销定况将京考证住到施又光见境 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 疯狂555 {
            get {
                return ResourceManager.GetString("疯狂555", resourceCulture);
            }
        }
    }
}
